### ISSUE TITLE
文言を日本語に統一する

### ISSUE THREAD

**Issue by ahuglajbclajep** [prog-g/dcc-report#116]
## やること

- [ ] 文言を日本語に統一する

## なぜやるのか

英語と日本語が混ざっていて中途半端なため。

## 備考

- `n/a` -> `なし`
- `Note` -> `メモ`
- `#1` -> `メモ #1`
- `Write something down` -> 削除
- `+ Add` -> `新しいメモを追加`
- `ID & Name` -> `学籍番号・氏名`
- `ID:` -> `学籍番号`
- `Name:` -> `氏名`

**Comment by ahuglajbclajep** [comment]
@curegit 文言について何か意見ありますか？

**Comment by curegit** [comment]
- n/a のほうがカッコイイのと納まりがよいと思った（n/a だと数値フィールド感がでる && 全角表記が多いと文字が多く感じる）
- \+ Add -> + メモを追加
- ID
岐阜大 specific じゃない方がいいと思うので、学籍番号じゃなくてより大雑把に ID にしましょう。 

メモを１行にしたときに textarea 感が減ると思うので placeholder も `メモを記入...` ぐらいいるかもです。

**Comment by curegit** [comment]
日本語に全部すると、別PRで導入しようとしている英文フォントがダメになると思いました。

**Comment by ahuglajbclajep** [comment]
英文フォントに関しては把握してるので大丈夫です。

学籍番号を ID にするという話は、そもそも大学以外で使う場合に ID なるものが存在するのかと言う話にもなるので、とりあえず確定している現状のユースケースに合わせて学籍番号にしたほうが分かりやすいと思います。
`+ Add` の `+` を消したのは、`+` と `追加` で意味が被っており `+` を残す意味が薄いと考えたためです。

**Comment by curegit** [comment]
ではあとは code author にお任せします
